name: lpce
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - biopython
  - tqdm
  - joblib
  - json
  - yagmail
  - rsync
  - pathlib
  - pip
  - pip:
    - python-dotenv
    - tqdm
    - pytest
