n_jobs: 54

paths:
  raw_dir: /mnt/ligandpro/db/LPCE/raw/pdb
  processed_dir: /mnt/ligandpro/db/LPCE/processed
  ligands_dir: /mnt/ligandpro/db/LPCE/ligands
  bioml_dir: /mnt/ligandpro/db/LPCE/bioml
  separated_dir: /mnt/ligandpro/db/LPCE/separated
  final_dir: /mnt/ligandpro/db/LPCE/final
  obabel_path: /home/nikolenko/miniforge/bin/obabel

output_files:
  removed_files_json: data/removed_files.json
  complexes_json: data/complexes.json
  grouped_complexes_json: data/grouped_complexes.json
  site_info_json: data/site_info.json
  trash_ligands_json: data/trash_ligands_ion.json
  removed_ligands_summary_json: data/removed_ligands_summary.json
  filtered_ligands_json: data/filtered_ligands.json
  cleaned_complexes_json: data/cleaned_complexes.json

junk_ligands:
  threshold: 4

rsync:
  port: 33444
  host: rsync.rcsb.org

logging:
  log_file: logs/logfile.log
  log_file_tests: logs/logfile_tests.log


separator_params:
  interact_distance: 4.5       # Distance to consider an atom as interacting.
  ligand_ligand_distance: 0.5  # (4 angstrom) distance to consider ligands as part of the same group.
  rmsd_threshold: 2.0          # RMSD threshold to consider structures as similar.
  identity_threshold: 0.98     # Identity threshold to consider structures as similar.


foldseek:
  foldseek_log: logs/foldseek.log
  foldseek_path: /home/nikolenko/work/ligandpro/soft/protein/foldseek/bin/foldseek
  prostt5_path: /home/nikolenko/work/soft/prostt5_model
  identical_groups: data/identical_groups.json
  tmscore_threshold: 0.8       # TM-score threshold to consider structures as similar.
  fident_threshold: 0.8        # Identity threshold to consider structures as similar.
  n_jobs: 112                  # Number of threads to use.

email:
  user: ${oc.env:EMAIL_USER}
  password: ${oc.env:EMAIL_PASSWORD}
  recipient: Nikolenko.Sergei@icloud.com

buried:
  buried_threshold: 0.3       # Threshold for buried ligands.
  buried_distance_cutoff: 5.0 # Distance cutoff for buried ligands.


overlapping:
  overlapping_threshold: 0.5   # Distance to consider ligands as overlapping.

add_h_to_ligands: true
